# Generated by Django 5.1.1 on 2024-09-18 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_resume_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume_model',
            name='carrier_summery',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
